import os

from dotenv import load_dotenv

load_dotenv()


SERPER_URL = "https://google.serper.dev/search"
API_KEY = os.getenv("SERPER_API_KEY")


NUM_RESULTS_PER_QUERY = 10
REQUEST_TIMEOUT = 30


SEARCH_QUERIES = [
    '"electric utility" GIS',
    '"electric utility" "GIS modernization"',
    '"electric utility" "GIS system"',
    '"electric utility" "geospatial data"',
    '"electric utility" "spatial data"',
    '"electric utility" "GIS mapping"',
    '"electric utility" "network GIS"',
    '"electric utility" "Utility Network"',
    '"electric utility" Esri GIS',
    '"electric utility" ArcGIS',
    '"electric utility" "distribution network" GIS',
    '"electric utility" "electric grid" GIS',
    '"electric utility" "asset mapping" GIS',
    '"electric utility" "asset management"',
    '"electric utility" "asset management system"',
    '"electric utility" "grid asset management"',
    '"electric utility" "asset data"',
    '"electric utility" "asset inventory"',
    '"electric utility" "infrastructure management"',
    '"electric utility" "distribution assets"',
    '"electric utility" "asset condition"',
    '"electric utility" "asset health"',
    '"electric utility" "asset lifecycle"',
    '"electric utility" IoT',
    '"electric utility" "IoT sensors"',
    '"electric utility" "smart sensors"',
    '"electric utility" telemetry',
    '"electric utility" "remote monitoring"',
    '"electric utility" "real-time monitoring"',
    '"electric utility" "grid sensors"',
    '"electric utility" "connected assets"',
    '"electric utility" "edge computing"',
    '"electric utility" "sensor data"',
    '"electric utility" AI',
    '"electric utility" "artificial intelligence"',
    '"electric utility" "machine learning"',
    '"electric utility" "AI system"',
    '"electric utility" "AI platform"',
    '"electric utility" "predictive analytics"',
    '"electric utility" "predictive maintenance"',
    '"electric utility" "AI predictive maintenance"',
    '"electric utility" "computer vision"',
    '"electric utility" "AI optimization"',
    '"electric utility" "intelligent asset management"',
    '"electric utility" "data platform"',
    '"electric utility" "data management"',
    '"electric utility" "data integration"',
    '"electric utility" "data architecture"',
    '"electric utility" "data analytics"',
    '"electric utility" "utility data"',
    '"electric utility" "asset data management"',
    '"electric utility" "data modernization"',
    '"electric utility" "data integration platform"',
    '"electric utility" "enterprise data"',
    '"electric utility" "cloud data platform"',
    '"electric utility" SCADA',
    '"electric utility" "SCADA modernization"',
    '"electric utility" "SCADA system"',
    '"electric utility" "operational technology"',
    '"electric utility" OT modernization',
    '"electric utility" "OT data"',
    '"electric utility" "SCADA data"',
    '"electric utility" "real-time grid data"',
    '"electric utility" "control system"',
    '"electric utility" "grid monitoring"',
    '"electric utility" AMI',
    '"electric utility" "advanced metering infrastructure"',
    '"electric utility" "smart meter"',
    '"electric utility" "smart grid"',
    '"electric utility" "smart grid modernization"',
    '"electric utility" "grid modernization"',
    '"electric utility" "digital grid"',
    '"electric utility" "grid digitalization"',
    '"electric utility" "distribution automation"',
    '"electric utility" "grid automation"',
    '"electric utility" modernization',
    '"electric utility" "digital transformation"',
    '"electric utility" "technology modernization"',
    '"electric utility" "legacy system"',
    '"electric utility" "legacy systems"',
    '"electric utility" "legacy infrastructure"',
    '"electric utility" "system replacement"',
    '"electric utility" "system integration"',
    '"electric utility" "technology upgrade"',
    '"electric utility" "enterprise modernization"',
    '"electric utility" "distribution planning"',
    '"electric utility" "distribution system"',
    '"electric utility" "grid planning"',
    '"electric utility" "grid analysis"',
    '"electric utility" "load forecasting"',
    '"electric utility" "grid reliability"',
    '"electric utility" "outage management"',
    '"electric utility" "distribution management system"',
    '"electric utility" DMS',
    '"electric utility" ADMS',
    '"electric utility" "outage management"',
    '"electric utility" OMS',
    '"electric utility" "field operations"',
    '"electric utility" "field data"',
    '"electric utility" "mobile GIS"',
    '"electric utility" "field service"',
    '"electric utility" "work management"',
    '"electric utility" "work order management"',
    '"electric utility" "field inspection"',
    '"electric utility" "remote inspection"',
    '"electric utility" "vegetation management"',
    '"electric utility" "vegetation monitoring"',
    '"electric utility" "line inspection"',
    '"electric utility" "asset inspection"',
    '"electric utility" "drone inspection"',
    '"electric utility" drone GIS',
    '"electric utility" "drone data"',
    '"electric utility" "AI inspection"',
    '"electric utility" "automated inspection"',
    '"electric utility" "infrastructure inspection"',
    '"electric utility" reliability AI',
    '"electric utility" reliability analytics',
    '"electric utility" "failure prediction"',
    '"electric utility" "failure detection"',
    '"electric utility" "fault detection"',
    '"electric utility" "condition monitoring"',
    '"electric utility" "predictive maintenance"',
    '"electric utility" "equipment failure"',
    '"electric utility" "grid resilience"',
    '"electric utility" "reliability improvement"',
    '"electric utility" DER',
    '"electric utility" "distributed energy resources"',
    '"electric utility" solar GIS',
    '"electric utility" "solar integration"',
    '"electric utility" "battery storage"',
    '"electric utility" "energy storage"',
    '"electric utility" "DERMS"',
    '"electric utility" "distributed generation"',
    '"electric utility" "renewable integration"',
    '"electric utility" "grid flexibility"',
    '"electric utility" cloud GIS',
    '"electric utility" "cloud platform"',
    '"electric utility" "cloud modernization"',
    '"electric utility" SaaS',
    '"electric utility" "digital platform"',
    '"electric utility" "enterprise platform"',
    '"electric utility" "cloud data"',
    '"electric utility" "GIS cloud"',
    '"electric utility" "digital twin"',
    '"electric utility" "grid digital twin"',
    '"electric utility" RFP GIS',
    '"electric utility" RFP "asset management"',
    '"electric utility" RFP IoT',
    '"electric utility" RFP AI',
    '"electric utility" RFP "data platform"',
    '"electric utility" RFP SCADA',
    '"electric utility" RFP "grid modernization"',
    '"electric utility" RFP "smart grid"',
    '"electric utility" RFP "mobile GIS"',
    '"electric utility" RFP "predictive maintenance"',
    '"electric utility" "aging infrastructure"',
    '"electric utility" "aging grid"',
    '"electric utility" "data silos"',
    '"electric utility" "poor data quality"',
    '"electric utility" "inaccurate asset data"',
    '"electric utility" "manual processes"',
    '"electric utility" "legacy data"',
    '"electric utility" "data challenges"',
    '"electric utility" "GIS challenges"',
    '"electric utility" "operational challenges"',
]


DEDUPLICATE_RESULTS = True
