import os

from dotenv import load_dotenv

load_dotenv()


HEADERS = {
    "User-Agent": ("Mozilla/5.0 " "(compatible; ValtirenMarketIntelligence/1.0)")
}

REQUEST_TIMEOUT = 30


CONTEXT_SIGNALS = [
    "electric utility",
    "electric utilities",
    "electric power utility",
    "power utility",
    "electric cooperative",
    "municipal electric utility",
    "public power utility",
    "electric distribution",
    "electric transmission",
    "power distribution",
    "power transmission",
    "electric grid",
    "power grid",
    "distribution grid",
    "transmission grid",
    "electric power system",
    "distribution system",
    "transmission system",
    "substation",
    "feeder",
    "power line",
    "electric meter",
    "smart meter",
]


TECHNOLOGY_SIGNALS = {
    "GIS": [
        "gis",
        "geographic information system",
        "geospatial",
        "geospatial data",
        "spatial data",
        "utility gis",
        "electric utility gis",
        "electric grid gis",
        "network gis",
        "mobile gis",
    ],
    "Utility Network": [
        "utility network",
        "arcgis utility network",
        "esri utility network",
        "utility network migration",
        "utility network implementation",
        "utility network model",
    ],
    "Electric Network Mapping": [
        "electric network mapping",
        "distribution network mapping",
        "distribution system mapping",
        "grid mapping",
        "feeder mapping",
        "circuit mapping",
        "electrical network model",
        "network model",
    ],
    "Grid Asset Management": [
        "asset management",
        "electric utility asset management",
        "grid asset management",
        "asset inventory",
        "asset tracking",
        "asset lifecycle management",
        "asset health",
        "asset condition",
        "asset registry",
    ],
    "Distribution Assets": [
        "distribution assets",
        "utility poles",
        "power poles",
        "transformers",
        "distribution transformers",
        "substation assets",
        "switchgear",
        "reclosers",
        "feeders",
        "transmission lines",
        "distribution lines",
    ],
    "SCADA": [
        "scada",
        "supervisory control and data acquisition",
        "scada system",
        "scada modernization",
        "scada integration",
        "scada data",
    ],
    "OT / Grid Operations": [
        "operational technology",
        "ot systems",
        "ot modernization",
        "grid operations",
        "control systems",
        "industrial control system",
        "ics",
    ],
    "ADMS": [
        "advanced distribution management system",
        "adms",
        "advanced distribution management",
    ],
    "Distribution Management": [
        "distribution management system",
        "dms",
        "distribution automation",
        "distribution operations",
        "distribution control",
    ],
    "Outage Management": [
        "outage management system",
        "oms",
        "outage management",
        "outage response",
        "outage restoration",
        "fault location",
        "fault isolation",
        "service restoration",
    ],
    "AMI": [
        "advanced metering infrastructure",
        "ami system",
        "ami network",
        "ami modernization",
        "smart meter",
        "smart metering",
        "meter data management",
        "meter data",
    ],
    "MDMS": [
        "meter data management system",
        "mdms",
        "meter data management",
        "meter analytics",
    ],
    "Grid IoT": [
        "internet of things",
        "iot",
        "utility iot",
        "grid iot",
        "iot sensors",
        "smart sensors",
        "connected grid",
        "connected assets",
        "sensor network",
    ],
    "Grid Monitoring": [
        "grid monitoring",
        "real-time grid monitoring",
        "remote monitoring",
        "remote asset monitoring",
        "condition monitoring",
        "equipment monitoring",
        "transformer monitoring",
        "line monitoring",
    ],
    "AI / Machine Learning": [
        "artificial intelligence",
        "machine learning",
        "deep learning",
        "ai platform",
        "ai system",
        "machine learning model",
        "predictive analytics",
        "predictive modeling",
    ],
    "Predictive Maintenance": [
        "predictive maintenance",
        "predictive asset management",
        "equipment failure prediction",
        "failure prediction",
        "condition-based maintenance",
        "condition based maintenance",
        "asset failure prediction",
    ],
    "Computer Vision": [
        "computer vision",
        "image recognition",
        "automated image analysis",
        "visual inspection",
        "ai inspection",
        "automated inspection",
    ],
    "Utility Data Platform": [
        "utility data platform",
        "electric utility data platform",
        "grid data platform",
        "energy data platform",
        "enterprise data platform",
        "data platform",
    ],
    "Data Integration": [
        "data integration",
        "system integration",
        "enterprise integration",
        "data interoperability",
        "system interoperability",
        "api integration",
        "data exchange",
    ],
    "Grid Analytics": [
        "grid analytics",
        "electric grid analytics",
        "distribution analytics",
        "utility analytics",
        "energy analytics",
        "asset analytics",
        "operational analytics",
    ],
    "Data Management": [
        "utility data management",
        "grid data management",
        "asset data management",
        "data governance",
        "data quality",
        "master data management",
    ],
    "Cloud": [
        "cloud migration",
        "cloud platform",
        "cloud infrastructure",
        "cloud computing",
        "utility cloud",
        "cloud modernization",
        "cloud-based utility",
    ],
    "Digital Twin": [
        "digital twin",
        "grid digital twin",
        "electric grid digital twin",
        "utility digital twin",
        "network digital twin",
    ],
    "Smart Grid": [
        "smart grid",
        "smart grid technology",
        "smart grid modernization",
        "digital grid",
        "grid digitalization",
        "grid digitization",
        "intelligent grid",
    ],
    "Grid Automation": [
        "grid automation",
        "distribution automation",
        "substation automation",
        "automated switching",
        "automated fault isolation",
        "remote switching",
    ],
    "DER": [
        "distributed energy resources",
        "der",
        "distributed generation",
        "distributed energy",
        "der integration",
    ],
    "DERMS": [
        "distributed energy resource management system",
        "derms",
        "der management system",
    ],
    "Renewable Grid Integration": [
        "solar integration",
        "renewable integration",
        "renewable energy integration",
        "grid integration",
        "renewable grid",
        "distributed solar",
        "battery storage",
        "energy storage",
    ],
    "Drone Inspection": [
        "drone inspection",
        "uav inspection",
        "unmanned aerial vehicle inspection",
        "drone data",
        "uav data",
        "drone mapping",
    ],
    "Remote Sensing": [
        "remote sensing",
        "satellite imagery",
        "aerial imagery",
        "lidar",
        "lidar data",
    ],
    "Mobile Workforce": [
        "mobile gis",
        "mobile workforce",
        "field mobility",
        "field service management",
        "mobile workforce management",
        "field operations platform",
    ],
    "Field Data Collection": [
        "field data collection",
        "digital field inspection",
        "mobile data collection",
        "electronic field inspection",
        "field inspection system",
    ],
}


PROBLEM_SIGNALS = {
    "Aging Grid": [
        "aging grid",
        "ageing grid",
        "aging infrastructure",
        "ageing infrastructure",
        "aging assets",
        "aging equipment",
        "aging electrical infrastructure",
        "aging distribution system",
    ],
    "Grid Reliability": [
        "grid reliability",
        "reliability challenges",
        "reliability improvement",
        "reliability issues",
        "system reliability",
        "distribution reliability",
        "power reliability",
    ],
    "Legacy Systems": [
        "legacy system",
        "legacy systems",
        "legacy infrastructure",
        "legacy technology",
        "legacy software",
        "outdated system",
        "obsolete system",
        "aging software",
    ],
    "Technology Modernization": [
        "technology modernization",
        "system modernization",
        "platform modernization",
        "digital modernization",
        "technology upgrade",
        "system replacement",
        "platform replacement",
    ],
    "GIS Modernization": [
        "gis modernization",
        "gis migration",
        "gis replacement",
        "gis upgrade",
        "gis implementation",
        "utility network migration",
        "geospatial modernization",
    ],
    "Poor Spatial Data": [
        "inaccurate gis data",
        "inaccurate spatial data",
        "poor gis data",
        "outdated gis data",
        "incomplete gis data",
        "inaccurate asset locations",
        "outdated mapping",
        "incomplete mapping",
    ],
    "Data Silos": [
        "data silos",
        "siloed data",
        "isolated systems",
        "disconnected systems",
        "fragmented data",
        "data fragmentation",
    ],
    "Data Integration": [
        "data integration",
        "system integration",
        "integration challenges",
        "interoperability challenges",
        "systems do not integrate",
        "lack of integration",
    ],
    "Data Quality": [
        "data quality",
        "poor data quality",
        "inaccurate data",
        "incomplete data",
        "inconsistent data",
        "duplicate data",
        "outdated data",
        "missing data",
    ],
    "Manual Processes": [
        "manual process",
        "manual processes",
        "manual workflow",
        "manual workflows",
        "paper-based",
        "paper based",
        "manual data entry",
        "spreadsheet-based",
        "spreadsheet based",
    ],
    "Asset Management Problems": [
        "asset management challenges",
        "asset management issues",
        "poor asset management",
        "asset inventory challenges",
        "incomplete asset inventory",
        "asset tracking challenges",
        "unknown asset condition",
    ],
    "Predictive Maintenance": [
        "predictive maintenance",
        "condition monitoring",
        "condition-based maintenance",
        "condition based maintenance",
        "preventive maintenance",
        "equipment failure",
        "unexpected equipment failure",
        "unplanned maintenance",
    ],
    "Outage Problems": [
        "frequent outages",
        "power outages",
        "outage management challenges",
        "outage response challenges",
        "long outage duration",
        "outage restoration",
        "unplanned outages",
        "service interruptions",
    ],
    "Field Operations": [
        "field operations challenges",
        "field workforce challenges",
        "field data challenges",
        "manual field inspection",
        "manual inspections",
        "field productivity",
        "field efficiency",
    ],
    "Vegetation Management": [
        "vegetation management",
        "vegetation monitoring",
        "vegetation encroachment",
        "vegetation inspection",
        "tree trimming",
        "right of way vegetation",
        "vegetation risk",
    ],
    "Grid Modernization": [
        "grid modernization",
        "grid modernisation",
        "electric grid modernization",
        "distribution modernization",
        "distribution system modernization",
        "grid upgrade",
        "distribution grid upgrade",
        "electrical infrastructure modernization",
    ],
    "OT Cybersecurity": [
        "ot cybersecurity",
        "scada cybersecurity",
        "industrial cybersecurity",
        "grid cybersecurity",
        "utility cybersecurity",
        "operational technology security",
    ],
}


OPPORTUNITY_SIGNALS = {
    "RFP": [
        "request for proposal",
        "rfp",
        "request for bids",
        "rfq",
        "solicitation",
        "bid opportunity",
        "competitive procurement",
    ],
    "Modernization Project": [
        "modernization project",
        "modernization initiative",
        "digital transformation",
        "technology transformation",
        "system implementation",
        "platform implementation",
    ],
    "Capital Investment": [
        "capital improvement",
        "capital investment",
        "capital project",
        "infrastructure investment",
        "grid investment",
    ],
    "Pilot Project": [
        "pilot project",
        "pilot program",
        "proof of concept",
        "poc",
        "demonstration project",
    ],
    "Vendor Search": [
        "seeking vendor",
        "looking for vendor",
        "technology vendor",
        "solution provider",
        "software vendor",
        "implementation partner",
    ],
}
